// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  string                 `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StartSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartSessionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *StartSessionRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Capabilities  string                 `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type ExecutePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PlanJson      string                 `protobuf:"bytes,3,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanRequest) Reset() {
	*x = ExecutePlanRequest{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanRequest) ProtoMessage() {}

func (x *ExecutePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutePlanRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutePlanRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecutePlanRequest) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type ExecutePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanResponse) Reset() {
	*x = ExecutePlanResponse{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanResponse) ProtoMessage() {}

func (x *ExecutePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutePlanResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecutePlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPlanRequest) Reset() {
	*x = CancelPlanRequest{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanRequest) ProtoMessage() {}

func (x *CancelPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanRequest.ProtoReflect.Descriptor instead.
func (*CancelPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPlanRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CancelPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPlanResponse) Reset() {
	*x = CancelPlanResponse{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanResponse) ProtoMessage() {}

func (x *CancelPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanResponse.ProtoReflect.Descriptor instead.
func (*CancelPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Issues        []*Issue               `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *Issue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_orchestrator_proto protoreflect.FileDescriptor

const file_pkg_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/orchestrator.proto\x12\x1amobile_mcp.v1.orchestrator\"\x81\x02\n" +
	"\x13StartSessionRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12S\n" +
	"\x06labels\x18\x03 \x03(\v2;.mobile_mcp.v1.orchestrator.StartSessionRequest.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\x04 \x01(\tR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\fcapabilities\x18\x02 \x01(\tR\fcapabilities\"k\n" +
	"\x12ExecutePlanRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1b\n" +
	"\tplan_json\x18\x03 \x01(\tR\bplanJson\"H\n" +
	"\x13ExecutePlanResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\".\n" +
	"\x11CancelPlanRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\".\n" +
	"\x12CancelPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"h\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\x06issues\x18\x02 \x03(\v2!.mobile_mcp.v1.orchestrator.IssueR\x06issues\"Q\n" +
	"\x05Issue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xce\x03\n" +
	"\fOrchestrator\x12q\n" +
	"\fStartSession\x12/.mobile_mcp.v1.orchestrator.StartSessionRequest\x1a0.mobile_mcp.v1.orchestrator.StartSessionResponse\x12n\n" +
	"\vExecutePlan\x12..mobile_mcp.v1.orchestrator.ExecutePlanRequest\x1a/.mobile_mcp.v1.orchestrator.ExecutePlanResponse\x12k\n" +
	"\n" +
	"CancelPlan\x12-.mobile_mcp.v1.orchestrator.CancelPlanRequest\x1a..mobile_mcp.v1.orchestrator.CancelPlanResponse\x12n\n" +
	"\vHealthCheck\x12..mobile_mcp.v1.orchestrator.HealthCheckRequest\x1a/.mobile_mcp.v1.orchestrator.HealthCheckResponseB5Z3github.com/mcp/mobile-worker/pkg/proto/orchestratorb\x06proto3"

var (
	file_pkg_proto_orchestrator_proto_rawDescOnce sync.Once
	file_pkg_proto_orchestrator_proto_rawDescData []byte
)

func file_pkg_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_pkg_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_orchestrator_proto_rawDesc), len(file_pkg_proto_orchestrator_proto_rawDesc)))
	})
	return file_pkg_proto_orchestrator_proto_rawDescData
}

var file_pkg_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_orchestrator_proto_goTypes = []any{
	(*StartSessionRequest)(nil),  // 0: mobile_mcp.v1.orchestrator.StartSessionRequest
	(*StartSessionResponse)(nil), // 1: mobile_mcp.v1.orchestrator.StartSessionResponse
	(*ExecutePlanRequest)(nil),   // 2: mobile_mcp.v1.orchestrator.ExecutePlanRequest
	(*ExecutePlanResponse)(nil),  // 3: mobile_mcp.v1.orchestrator.ExecutePlanResponse
	(*CancelPlanRequest)(nil),    // 4: mobile_mcp.v1.orchestrator.CancelPlanRequest
	(*CancelPlanResponse)(nil),   // 5: mobile_mcp.v1.orchestrator.CancelPlanResponse
	(*HealthCheckRequest)(nil),   // 6: mobile_mcp.v1.orchestrator.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 7: mobile_mcp.v1.orchestrator.HealthCheckResponse
	(*Issue)(nil),                // 8: mobile_mcp.v1.orchestrator.Issue
	nil,                          // 9: mobile_mcp.v1.orchestrator.StartSessionRequest.LabelsEntry
}
var file_pkg_proto_orchestrator_proto_depIdxs = []int32{
	9, // 0: mobile_mcp.v1.orchestrator.StartSessionRequest.labels:type_name -> mobile_mcp.v1.orchestrator.StartSessionRequest.LabelsEntry
	8, // 1: mobile_mcp.v1.orchestrator.HealthCheckResponse.issues:type_name -> mobile_mcp.v1.orchestrator.Issue
	0, // 2: mobile_mcp.v1.orchestrator.Orchestrator.StartSession:input_type -> mobile_mcp.v1.orchestrator.StartSessionRequest
	2, // 3: mobile_mcp.v1.orchestrator.Orchestrator.ExecutePlan:input_type -> mobile_mcp.v1.orchestrator.ExecutePlanRequest
	4, // 4: mobile_mcp.v1.orchestrator.Orchestrator.CancelPlan:input_type -> mobile_mcp.v1.orchestrator.CancelPlanRequest
	6, // 5: mobile_mcp.v1.orchestrator.Orchestrator.HealthCheck:input_type -> mobile_mcp.v1.orchestrator.HealthCheckRequest
	1, // 6: mobile_mcp.v1.orchestrator.Orchestrator.StartSession:output_type -> mobile_mcp.v1.orchestrator.StartSessionResponse
	3, // 7: mobile_mcp.v1.orchestrator.Orchestrator.ExecutePlan:output_type -> mobile_mcp.v1.orchestrator.ExecutePlanResponse
	5, // 8: mobile_mcp.v1.orchestrator.Orchestrator.CancelPlan:output_type -> mobile_mcp.v1.orchestrator.CancelPlanResponse
	7, // 9: mobile_mcp.v1.orchestrator.Orchestrator.HealthCheck:output_type -> mobile_mcp.v1.orchestrator.HealthCheckResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_orchestrator_proto_init() }
func file_pkg_proto_orchestrator_proto_init() {
	if File_pkg_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_orchestrator_proto_rawDesc), len(file_pkg_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_pkg_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_pkg_proto_orchestrator_proto = out.File
	file_pkg_proto_orchestrator_proto_goTypes = nil
	file_pkg_proto_orchestrator_proto_depIdxs = nil
}
