FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o orchestrator cmd/orchestrator/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/orchestrator .
CMD ["./orchestrator"]
