# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1 import mcp_pb2 as v1_dot_mcp__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub(object):
    """The service definition for the Mobile Control Platform (MCP).
    モバイルコントロールプラットフォーム（MCP）のサービス定義。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableDevices = channel.unary_unary(
                '/mcp.v1.MCPService/GetAvailableDevices',
                request_serializer=v1_dot_mcp__pb2.GetAvailableDevicesRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.GetAvailableDevicesResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/mcp.v1.MCPService/StartSession',
                request_serializer=v1_dot_mcp__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/mcp.v1.MCPService/EndSession',
                request_serializer=v1_dot_mcp__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.GetScreenLayout = channel.unary_unary(
                '/mcp.v1.MCPService/GetScreenLayout',
                request_serializer=v1_dot_mcp__pb2.GetScreenLayoutRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.GetScreenLayoutResponse.FromString,
                _registered_method=True)
        self.TapElement = channel.unary_unary(
                '/mcp.v1.MCPService/TapElement',
                request_serializer=v1_dot_mcp__pb2.TapElementRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.TapElementResponse.FromString,
                _registered_method=True)
        self.InputText = channel.unary_unary(
                '/mcp.v1.MCPService/InputText',
                request_serializer=v1_dot_mcp__pb2.InputTextRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.InputTextResponse.FromString,
                _registered_method=True)
        self.Swipe = channel.unary_unary(
                '/mcp.v1.MCPService/Swipe',
                request_serializer=v1_dot_mcp__pb2.SwipeRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.SwipeResponse.FromString,
                _registered_method=True)
        self.GetElementAttribute = channel.unary_unary(
                '/mcp.v1.MCPService/GetElementAttribute',
                request_serializer=v1_dot_mcp__pb2.GetElementAttributeRequest.SerializeToString,
                response_deserializer=v1_dot_mcp__pb2.GetElementAttributeResponse.FromString,
                _registered_method=True)


class MCPServiceServicer(object):
    """The service definition for the Mobile Control Platform (MCP).
    モバイルコントロールプラットフォーム（MCP）のサービス定義。
    """

    def GetAvailableDevices(self, request, context):
        """Get a list of available devices managed by the server.
        サーバーによって管理されている利用可能なデバイスのリストを取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Start a new session on a specific device with a specific app.
        特定のデバイスで特定のアプリの新しいセッションを開始します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """End the current session.
        現在のセッションを終了します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScreenLayout(self, request, context):
        """Get the current UI layout/hierarchy of the screen.
        現在の画面のUIレイアウト/階層を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TapElement(self, request, context):
        """Tap an element on the screen identified by its description.
        画面上の要素をその説明によって識別し、タップします。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InputText(self, request, context):
        """Input text into an element identified by its description.
        要素をその説明によって識別し、テキストを入力します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swipe(self, request, context):
        """Perform a swipe gesture on the screen.
        画面上でスワイプジェスチャーを実行します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetElementAttribute(self, request, context):
        """Get a specific attribute from a UI element.
        UI要素から特定の属性を取得します。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableDevices,
                    request_deserializer=v1_dot_mcp__pb2.GetAvailableDevicesRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.GetAvailableDevicesResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=v1_dot_mcp__pb2.StartSessionRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.StartSessionResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=v1_dot_mcp__pb2.EndSessionRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.EndSessionResponse.SerializeToString,
            ),
            'GetScreenLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScreenLayout,
                    request_deserializer=v1_dot_mcp__pb2.GetScreenLayoutRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.GetScreenLayoutResponse.SerializeToString,
            ),
            'TapElement': grpc.unary_unary_rpc_method_handler(
                    servicer.TapElement,
                    request_deserializer=v1_dot_mcp__pb2.TapElementRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.TapElementResponse.SerializeToString,
            ),
            'InputText': grpc.unary_unary_rpc_method_handler(
                    servicer.InputText,
                    request_deserializer=v1_dot_mcp__pb2.InputTextRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.InputTextResponse.SerializeToString,
            ),
            'Swipe': grpc.unary_unary_rpc_method_handler(
                    servicer.Swipe,
                    request_deserializer=v1_dot_mcp__pb2.SwipeRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.SwipeResponse.SerializeToString,
            ),
            'GetElementAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElementAttribute,
                    request_deserializer=v1_dot_mcp__pb2.GetElementAttributeRequest.FromString,
                    response_serializer=v1_dot_mcp__pb2.GetElementAttributeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.v1.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.v1.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService(object):
    """The service definition for the Mobile Control Platform (MCP).
    モバイルコントロールプラットフォーム（MCP）のサービス定義。
    """

    @staticmethod
    def GetAvailableDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/GetAvailableDevices',
            v1_dot_mcp__pb2.GetAvailableDevicesRequest.SerializeToString,
            v1_dot_mcp__pb2.GetAvailableDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/StartSession',
            v1_dot_mcp__pb2.StartSessionRequest.SerializeToString,
            v1_dot_mcp__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/EndSession',
            v1_dot_mcp__pb2.EndSessionRequest.SerializeToString,
            v1_dot_mcp__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScreenLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/GetScreenLayout',
            v1_dot_mcp__pb2.GetScreenLayoutRequest.SerializeToString,
            v1_dot_mcp__pb2.GetScreenLayoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TapElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/TapElement',
            v1_dot_mcp__pb2.TapElementRequest.SerializeToString,
            v1_dot_mcp__pb2.TapElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InputText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/InputText',
            v1_dot_mcp__pb2.InputTextRequest.SerializeToString,
            v1_dot_mcp__pb2.InputTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Swipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/Swipe',
            v1_dot_mcp__pb2.SwipeRequest.SerializeToString,
            v1_dot_mcp__pb2.SwipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetElementAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.MCPService/GetElementAttribute',
            v1_dot_mcp__pb2.GetElementAttributeRequest.SerializeToString,
            v1_dot_mcp__pb2.GetElementAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
