// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Capabilities  string                 `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_pkg_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_pkg_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExecutePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PlanJson      string                 `protobuf:"bytes,3,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanRequest) Reset() {
	*x = ExecutePlanRequest{}
	mi := &file_pkg_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanRequest) ProtoMessage() {}

func (x *ExecutePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutePlanRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutePlanRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecutePlanRequest) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type PlanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	StepIndex     int32                  `protobuf:"varint,2,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanEvent) Reset() {
	*x = PlanEvent{}
	mi := &file_pkg_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanEvent) ProtoMessage() {}

func (x *PlanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanEvent.ProtoReflect.Descriptor instead.
func (*PlanEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PlanEvent) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PlanEvent) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *PlanEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlanEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlanEvent) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type CancelPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPlanRequest) Reset() {
	*x = CancelPlanRequest{}
	mi := &file_pkg_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanRequest) ProtoMessage() {}

func (x *CancelPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanRequest.ProtoReflect.Descriptor instead.
func (*CancelPlanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPlanRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CancelPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPlanResponse) Reset() {
	*x = CancelPlanResponse{}
	mi := &file_pkg_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanResponse) ProtoMessage() {}

func (x *CancelPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanResponse.ProtoReflect.Descriptor instead.
func (*CancelPlanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pkg_proto_worker_proto protoreflect.FileDescriptor

const file_pkg_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/worker.proto\x12\x14mobile_mcp.v1.worker\"X\n" +
	"\x13StartSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\fcapabilities\x18\x02 \x01(\tR\fcapabilities\"0\n" +
	"\x14StartSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"k\n" +
	"\x12ExecutePlanRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1b\n" +
	"\tplan_json\x18\x03 \x01(\tR\bplanJson\"\xf2\x01\n" +
	"\tPlanEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"step_index\x18\x02 \x01(\x05R\tstepIndex\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12F\n" +
	"\ametrics\x18\x05 \x03(\v2,.mobile_mcp.v1.worker.PlanEvent.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x11CancelPlanRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\".\n" +
	"\x12CancelPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x90\x03\n" +
	"\x06Worker\x12e\n" +
	"\fStartSession\x12).mobile_mcp.v1.worker.StartSessionRequest\x1a*.mobile_mcp.v1.worker.StartSessionResponse\x12Z\n" +
	"\vExecutePlan\x12(.mobile_mcp.v1.worker.ExecutePlanRequest\x1a\x1f.mobile_mcp.v1.worker.PlanEvent0\x01\x12_\n" +
	"\n" +
	"CancelPlan\x12'.mobile_mcp.v1.worker.CancelPlanRequest\x1a(.mobile_mcp.v1.worker.CancelPlanResponse\x12b\n" +
	"\vHealthCheck\x12(.mobile_mcp.v1.worker.HealthCheckRequest\x1a).mobile_mcp.v1.worker.HealthCheckResponseB/Z-github.com/mcp/mobile-worker/pkg/proto/workerb\x06proto3"

var (
	file_pkg_proto_worker_proto_rawDescOnce sync.Once
	file_pkg_proto_worker_proto_rawDescData []byte
)

func file_pkg_proto_worker_proto_rawDescGZIP() []byte {
	file_pkg_proto_worker_proto_rawDescOnce.Do(func() {
		file_pkg_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_worker_proto_rawDesc), len(file_pkg_proto_worker_proto_rawDesc)))
	})
	return file_pkg_proto_worker_proto_rawDescData
}

var file_pkg_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_worker_proto_goTypes = []any{
	(*StartSessionRequest)(nil),  // 0: mobile_mcp.v1.worker.StartSessionRequest
	(*StartSessionResponse)(nil), // 1: mobile_mcp.v1.worker.StartSessionResponse
	(*ExecutePlanRequest)(nil),   // 2: mobile_mcp.v1.worker.ExecutePlanRequest
	(*PlanEvent)(nil),            // 3: mobile_mcp.v1.worker.PlanEvent
	(*CancelPlanRequest)(nil),    // 4: mobile_mcp.v1.worker.CancelPlanRequest
	(*CancelPlanResponse)(nil),   // 5: mobile_mcp.v1.worker.CancelPlanResponse
	(*HealthCheckRequest)(nil),   // 6: mobile_mcp.v1.worker.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 7: mobile_mcp.v1.worker.HealthCheckResponse
	nil,                          // 8: mobile_mcp.v1.worker.PlanEvent.MetricsEntry
}
var file_pkg_proto_worker_proto_depIdxs = []int32{
	8, // 0: mobile_mcp.v1.worker.PlanEvent.metrics:type_name -> mobile_mcp.v1.worker.PlanEvent.MetricsEntry
	0, // 1: mobile_mcp.v1.worker.Worker.StartSession:input_type -> mobile_mcp.v1.worker.StartSessionRequest
	2, // 2: mobile_mcp.v1.worker.Worker.ExecutePlan:input_type -> mobile_mcp.v1.worker.ExecutePlanRequest
	4, // 3: mobile_mcp.v1.worker.Worker.CancelPlan:input_type -> mobile_mcp.v1.worker.CancelPlanRequest
	6, // 4: mobile_mcp.v1.worker.Worker.HealthCheck:input_type -> mobile_mcp.v1.worker.HealthCheckRequest
	1, // 5: mobile_mcp.v1.worker.Worker.StartSession:output_type -> mobile_mcp.v1.worker.StartSessionResponse
	3, // 6: mobile_mcp.v1.worker.Worker.ExecutePlan:output_type -> mobile_mcp.v1.worker.PlanEvent
	5, // 7: mobile_mcp.v1.worker.Worker.CancelPlan:output_type -> mobile_mcp.v1.worker.CancelPlanResponse
	7, // 8: mobile_mcp.v1.worker.Worker.HealthCheck:output_type -> mobile_mcp.v1.worker.HealthCheckResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_worker_proto_init() }
func file_pkg_proto_worker_proto_init() {
	if File_pkg_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_worker_proto_rawDesc), len(file_pkg_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_worker_proto_goTypes,
		DependencyIndexes: file_pkg_proto_worker_proto_depIdxs,
		MessageInfos:      file_pkg_proto_worker_proto_msgTypes,
	}.Build()
	File_pkg_proto_worker_proto = out.File
	file_pkg_proto_worker_proto_goTypes = nil
	file_pkg_proto_worker_proto_depIdxs = nil
}
